[package]
name = "example_serial_thread"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-channel = "2.2.0"
serial = "0.4.0"
serial-thread = "0.0.1"
tokio = "1.36.0"
